### ISSUE TITLE
logger line

### ISSUE THREAD

**Issue by wuxiaoxiaoshen** [apsdehal/go-logger#10] opened 2018-01-17 08:05 UTC
hi, 

#1 2018-01-18 00:07:37 log.go:25 ▶ WAR TransactionID=opcli InstancesID=main Message=This is test []

it seems the line is not correct，the line should be the line the number when i use log.DebugF 、log.WarningF .. and so on ?

**Comment by apsdehal** [comment] 2018-01-22 13:00
Didn't get you, can you explain more?

**Comment by yoni386** [comment] 2018-09-04 21:06
I think I saw it too. The actual src line is not correct. Actual line (src code line) is not corresponding to line printed by the logger.

**Comment by apsdehal** [comment] 2018-09-05 07:03
ok, got it. I will look into it this weekend.

**Comment by apsdehal** [comment] 2019-05-15 21:22
I am unable to reproduce this. The tests also test for corresponding line number. Thus, without proper example I will be unable to fix this. Closing this for now. If you are still facing the issue, please open another issue. Thanks.

**Closed by apsdehal** 2019-05-15 21:22 UTC
